# Generated by Django 6.0.1 on 2026-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
