# Generated by Django 6.0.1 on 2026-01-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_file_file_file_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resource_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
