# Generated by Django 6.0.1 on 2026-01-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cloud_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=100)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('limit_bytes', models.BigIntegerField(default=25769803776)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='storage_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storage.storageaccount'),
            preserve_default=False,
        ),
    ]
